// Generated by CoffeeScript 1.8.0
(function() {
  var config_custom, error, fs, get_config;

  fs = require('fs');

  config_custom = null;

  try {
    config_custom = require('../config.json');
  } catch (_error) {
    error = _error;
    console.log("there are no config file");
    throw error;
  }

  get_config = function(name) {
    return config_custom[name];
  };

  module.exports = get_config;

}).call(this);
